"""Context summarization middleware — LLM-driven history compression.

When conversation history exceeds `max_messages`, calls the LLM to compress
older messages into a concise summary, then replaces them with a single
[Summary] message, keeping the most recent `keep_recent` messages intact.

Supersedes the simple truncation in compaction.py.
"""

from __future__ import annotations

import logging
from typing import Any

from .llm_client import LLMClient, ModelConfig
from .middleware import AgentMiddleware, RuntimeState

logger = logging.getLogger(__name__)

_SUMMARIZE_PROMPT = """\
Summarize the following conversation concisely in markdown.
Keep: decisions made, files changed, errors encountered, current task status.
Output ONLY the summary, no preamble.

{history}"""


class SummarizationMiddleware(AgentMiddleware):
    """Compress conversation history via LLM when message count exceeds threshold.

    Replaces all but the most recent `keep_recent` messages with a single
    [Summary] message generated by the configured LLM.
    """

    def __init__(
        self,
        *,
        llm_client: LLMClient,
        model_config: ModelConfig,
        max_messages: int = 60,
        keep_recent: int = 10,
    ) -> None:
        self._llm_client = llm_client
        self._model_config = model_config
        self._max_messages = max_messages
        self._keep_recent = keep_recent

    async def before_model(self, state: RuntimeState) -> None:
        if len(state.messages) > self._max_messages:
            await self._compress(state)
            return
        if self._estimate_tokens(state.messages) > 40000:
            await self._compress(state)

    def _estimate_tokens(self, messages: list[dict[str, Any]]) -> int:
        total_chars = 0
        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, str):
                total_chars += len(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict):
                        total_chars += len(block.get("text", ""))
                        total_chars += len(str(block.get("input", "")))
        return total_chars // 4

    async def _compress(self, state: RuntimeState) -> None:
        to_compress = state.messages[: -self._keep_recent]
        recent = state.messages[-self._keep_recent :]

        summary_text = await self._call_llm_summarize(to_compress)

        state.messages.clear()
        state.messages.append({
            "role": "user",
            "content": f"[Summary of earlier conversation]\n{summary_text}",
        })
        state.messages.extend(recent)
        logger.debug(
            "SummarizationMiddleware: compressed %d messages → 1 summary + %d recent",
            len(to_compress),
            len(recent),
        )

    async def _call_llm_summarize(self, messages: list[dict[str, Any]]) -> str:
        history_text = _format_messages_for_summary(messages)
        prompt = _SUMMARIZE_PROMPT.format(history=history_text)

        try:
            response = await self._llm_client.complete(
                messages=[{"role": "user", "content": prompt}],
                tools=[],
                model_config=self._model_config,
                system_prompt="You are a concise technical summarizer.",
                max_tokens=1024,
                temperature=0.3,
            )
            return response.text.strip() or "[Summary unavailable]"
        except Exception as exc:
            logger.warning("SummarizationMiddleware LLM call failed: %s", exc)
            return f"[Summary generation failed: {exc}]"


def _format_messages_for_summary(messages: list[dict[str, Any]]) -> str:
    """Convert message list to a readable text block for the summarization prompt."""
    parts: list[str] = []
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        if isinstance(content, str):
            parts.append(f"{role.upper()}: {content}")
        elif isinstance(content, list):
            # Handle structured content blocks (tool calls, tool results, etc.)
            texts: list[str] = []
            for block in content:
                if not isinstance(block, dict):
                    continue
                block_type = block.get("type", "")
                if block_type == "text":
                    texts.append(block.get("text", ""))
                elif block_type == "tool_use":
                    texts.append(f"[Tool call: {block.get('name', '?')}]")
                elif block_type == "tool_result":
                    result_content = block.get("content", "")
                    preview = result_content[:200] if len(result_content) > 200 else result_content
                    texts.append(f"[Tool result: {preview}]")
            parts.append(f"{role.upper()}: {'  '.join(texts)}")
    return "\n\n".join(parts)
